### ISSUE TITLE
[Syntax Highlight] String interpolation

### ISSUE THREAD

**Issue by senyaak** [TypeStrong/atom-typescript#1114]
After I've got version 10.1.10 the values have the same color as string
Exaple:

``` typescript
var a = "test";
console.log(`var a = ${a}`);
```

Curr behavior: The substring `${a}` has the same color as text

Expected behavior: `${}` and `a` have another color

UPD1. In some cases the value name get different color but $ and the brackets don't

**Comment by guncha** [comment]
The colors depend on the theme you're using and you can address it by adding something like this to your stylesheet:

```less
atom-text-editor::shadow {
  .source.ts, .source.tsx {
    .template-expression {
      &.begin, &.end {
        color: purple;
      }
    }
  }
}
```

**Comment by admosity** [comment]
I provided an example in #1113

![image](https://cloud.githubusercontent.com/assets/4655972/19823152/21250b94-9d35-11e6-9a97-97c998b6fc8a.png)

**Comment by admosity** [comment]
Here's my fuller configuration for monokai:

```less
@monokai-blue: #66d9ef;
@monokai-blue-light: #89BDFF;
@monokai-blue-lighter: lighten(@monokai-blue-light, 10%);
@monokai-gray: #595959;
@monokai-gray-darker: #383830;
@monokai-gray-darkest: #141411;
@monokai-gray-lightest: #595959;
@monokai-gray-light: #E6E6E6;
@monokai-green: #A6E22A;
@monokai-green-light: #A6E22E;
@monokai-grey-dark: #272822;
@monokai-magenta: #F92672;
@monokai-purple: #AE81FF;
@monokai-purple-light: #FD5FF1;
@monokai-yellow: #E6DB74;
@monokai-yellow-dark: #75715E;
@monokai-yellow-light: #F8F8F2;


  .source.tsx, .source.ts {
    // expression highlighting mixin
    .expressions() {
      .support {
        color: @monokai-blue;
      }
      .this {
        color: @monokai-purple;
        & ~ .property {
          color: @monokai-blue-lighter;
        }
      }
      .definition.variable.object {
        color: @monokai-blue-lighter;
      }
      .name.type {
        color: #a6e22e;
        text-decoration: underline;
      }
      .object-literal.key {
        color: lighten(@monokai-green, 25%);
      }
    }
    .string.template {
      .variable {
        color: white;
      }
      .punctuation.accessor {
        color: @monokai-magenta;
      }
      .template-expression {
        &.begin {
          color: @monokai-magenta;
        }
        &.end {
          color: @monokai-magenta;
        }
      }
      .expressions;
    }
    // GENERAL
    .expressions;
  }

```

![image](https://cloud.githubusercontent.com/assets/4655972/19823281/ca3d7964-9d35-11e6-98af-50c9bb95dcd0.png)
