### ISSUE TITLE
Ugly underlining of import dependency specifier names

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/atom-typescript#1454]
After switching from ide-typescript to atom-typescript, it is adding an ugly underline to my imports:

![screen shot 2018-10-09 at 5 51 01 pm](https://user-images.githubusercontent.com/297678/46706908-fd2ae500-cbeb-11e8-9ce1-b612d46cde64.png)

It'd be nice not to have those, they're visually harsh.

**Comment by lierdakil** [comment]
You can override styles in your stylesheet:
```less

atom-text-editor {
  .syntax--source.syntax--ts,
  .syntax--source.syntax--tsx {
    .syntax--import-equals,
    .syntax--import,
    .syntax--triple-slash {
      .syntax--string {
        text-decoration: none;
      }
    }
  }
}
```
