### ISSUE TITLE
Disable blinking TS compiler icon on bottom red corner

### ISSUE THREAD

**Issue by olegccc** [TypeStrong/atom-typescript#294]
Hi, is it possible to hide constantly blinking TS compiler icon? It really takes attention and prevents to work.
Thanks.

**Comment by basarat** [comment]
`v3.1.1` : 

You can now make it `lighter` e.g. put the following in *your* stylesheet:

```less
.atomts-main-panel{
    .section-pending {
        opacity: .2;
    }
}
```

![image](https://cloud.githubusercontent.com/assets/874898/7290162/f780c2aa-e9bd-11e4-8e54-dc59cebb1036.png)


I strongly recommend you don't make it zero because that would lead to confusion about *is atomts doing something or not?*.
