### ISSUE TITLE
Syntax ToolTip overflows window width

### ISSUE THREAD

**Issue by 0815fox** [TypeStrong/atom-typescript#919]
Even though I have a very large screen of 2560x1440, the ToolTip does not fit for long definitions, see screenshot.

I am on Ubuntu 14.04, multihead setup (screens side by side), the atom window is on the middle screen (DP-3), if that helps:
```
$ xrandr
Screen 0: minimum 8 x 8, current 7040 x 1440, maximum 16384 x 16384
VGA-0 disconnected (normal left inverted right x axis y axis)
LVDS-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 382mm x 215mm
   1920x1080      60.0*+
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 connected 2560x1440+1920+0 (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440      60.0*+
   2048x1152      60.0  
   1920x1200      59.9  
   1920x1080      60.0     59.9     50.0     30.0     25.0     24.0     60.1     60.0     50.0  
   1680x1050      60.0  
   1600x1200      60.0  
   1280x1024      75.0     60.0  
   1280x720       60.0     59.9     50.0  
   1200x960       59.9  
   1152x864       75.0  
   1024x768       75.0     60.0  
   800x600        75.0     60.3  
   720x576        50.0     50.1  
   720x480        59.9     60.1  
   640x480        75.0     59.9     59.9  
DP-4 disconnected (normal left inverted right x axis y axis)
DP-5 connected 2560x1440+4480+0 (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440      60.0*+
   2048x1152      60.0  
   1920x1200      59.9  
   1920x1080      60.0     59.9     50.0     30.0     25.0     24.0     60.1     60.0     50.0  
   1680x1050      60.0  
   1600x1200      60.0  
   1280x1024      75.0     60.0  
   1280x720       60.0     59.9     50.0  
   1200x960       59.9  
   1152x864       75.0  
   1024x768       75.0     60.0  
   800x600        75.0     60.3  
   720x576        50.0     50.1  
   720x480        59.9     60.1  
   640x480        75.0     59.9     59.9
```

![snapshot1](https://cloud.githubusercontent.com/assets/8955528/14486896/cd824536-015f-11e6-9e38-88de81def2a2.jpeg)

**Comment by orizens** [comment]
i experienced the same issue. 
I identified 2 cases where it happens and applying these css rules fix this:

```css
/* this is relevant for a one liner */
.atom-typescript-tooltip .tooltip-inner b {
    word-break: break-word;
    word-wrap: break-word;
    white-space: normal;
}
/* this is relevant for methods/tooltip with a description */
.atom-typescript-tooltip .tooltip-inner i {
    white-space: normal;
}
```
